# Set environment variables to be used in the build process
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# Hooks that will be run before any builds are done
before:
  hooks:
    - go mod tidy
    - go mod download

# Builds configuration
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/scdl/main.go
    binary: scdl

# Archive configurations
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    files:
      - README.md

# Checksum configuration
checksum:
  name_template: 'checksums.txt'

# Snapshot configuration
snapshot:
  name_template: '{{ .Tag }}-next'

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - 'LICENSE'
      - 'Merge pull request'
      - 'Merge branch'

# Homebrew configuration
brews:
  - repository:
      owner: imthaghost
      name: homebrew-scdl
    folder: Formula
    homepage: https://github.com/imthaghost/scdl
    description: "SoundCloud Music Downloader | Scdl is the fastest SoundCloud music downloading CLI tool. Scdl utilizes go routine pools which allows you to download any song from SoundCloud within seconds. There are extended features such as recursively downloading all songs from a given artist and grabbing song artwork."
